module.exports = [{
name:"eprevious",
type:"awaitedCommand",
code:`$if[$getuservar[esnipe_type]==channel]
$editMessage[$message[1];{author:$usertag[$get[author]]:$useravatar[$get[author]]}{field:Old Message:$replacetext[$replacetext[$checkcondition[$charcount[$get[old]]>=1024];true;Failed To Display Message(Too Large To Display In An Embed Field)];false;$get[old]]}{field:New Message:$replacetext[$replacetext[$checkcondition[$charcount[$get[message]]>=1024];true;Failed To Display Message(Too Large To Display In An Embed Field)];false;$get[message]]}{field:Message Link:[Click Here]($get[link])}{image:$get[image]}{color:RANDOM}{footer:Message Edited In #$channelname[$get[channel]] | Snipe $get[page]/$sub[$gettextsplitlength;1] | Edited at}{timestamp:$get[time]};$channelID]
$let[author;$advancedtextsplit[$getchannelvar[esnipe_author;$get[channel]];ᾟ;$get[page]]]
$let[message;$advancedtextsplit[$getchannelvar[esnipe_message;$get[channel]];ᾟ;$get[page]]]
$let[time;$advancedtextsplit[$getchannelvar[esnipe_time;$get[channel]];ᾟ;$get[page]]]
$let[image;$advancedtextsplit[$getchannelvar[esnipe_image;$get[channel]];ᾟ;$get[page]]]
$let[old;$advancedtextsplit[$getchannelvar[esnipe_omessage;$get[channel]];ᾟ;$get[page]]]
$let[link;$advancedtextsplit[$getchannelvar[esnipe_link;$get[channel]];ᾟ;$get[page]]]
$setuservar[esnipe_page;$get[page]]
$setuservar[esnipe_channel;$get[channel]]
$let[page;$replacetext[$replacetext[$checkcondition[$getuservar[esnipe_page]==1];true;$sub[$gettextsplitlength;1]];false;$sub[$getuservar[esnipe_page];1]]]
$textsplit[$getchannelvar[esnipe_message;$get[channel]];ᾟ]
$let[channel;$getuservar[esnipe_channel]]
$else
$editMessage[$message[1];{author:$usertag[$get[author]]:$useravatar[$get[author]]}{field:Old Message:$replacetext[$replacetext[$checkcondition[$charcount[$get[old]]>=1024];true;Failed To Display Message(Too Large To Display In An Embed Field)];false;$get[old]]}{field:New Message:$replacetext[$replacetext[$checkcondition[$charcount[$get[message]]>=1024];true;Failed To Display Message(Too Large To Display In An Embed Field)];false;$get[message]]}{field:Message Link:[Click Here]($get[link])}{image:$get[image]}{color:RANDOM}{footer:Message Edited In #$channelname[$get[channel]] | Snipe $get[page]/$sub[$gettextsplitlength;1] | Edited at}{timestamp:$get[time]};$channelID]
$let[author;$advancedtextsplit[$getservervar[esnipe_author];ᾟ;$get[page]]]
$let[message;$advancedtextsplit[$getservervar[esnipe_message];ᾟ;$get[page]]]
$let[old;$advancedtextsplit[$getservervar[esnipe_omessage];ᾟ;$get[page]]]
$let[link;$advancedtextsplit[$getservervar[esnipe_link];ᾟ;$get[page]]]
$let[time;$advancedtextsplit[$getservervar[esnipe_time];ᾟ;$get[page]]]
$let[image;$advancedtextsplit[$getservervar[esnipe_image];ᾟ;$get[page]]]
$setuservar[esnipe_page;$get[page]]
$setuservar[esnipe_channel]
$let[channel;$advancedtextsplit[$getservervar[esnipe_mchannel];ᾟ;$get[page]]]
$let[page;$replacetext[$replacetext[$checkcondition[$getuservar[esnipe_page]==1];true;$sub[$gettextsplitlength;1]];false;$sub[$getuservar[esnipe_page];1]]]
$textsplit[$getservervar[esnipe_message];ᾟ]
$endif`}]